version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: build.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
